const API_LOGIN_USER = '/loginUser';
const API_CHECK_SESSION_EXPIRED = '/checkExpired'
const API_GET_ALL_ACTIVE_USERS = '/getActiveUsers'
const API_GET_SESSION = '/getSession'
const API_GET_ASSIGNED_LETTERS = '/getAssignedLetters'
const API_SUBMIT_EXCHANGE_REQUEST = '/submitExchangeRequest'
const API_SUBMIT_EXCHANGE_RESPONSE = '/submitExchangeResponse'
const API_EXCHANGE_COMPLETED = '/exchangeCompleted'

module.exports={
    API_LOGIN_USER,API_CHECK_SESSION_EXPIRED,API_GET_ALL_ACTIVE_USERS,API_GET_SESSION,API_GET_ASSIGNED_LETTERS,
    API_SUBMIT_EXCHANGE_REQUEST,API_EXCHANGE_COMPLETED,API_SUBMIT_EXCHANGE_RESPONSE
}