const API_LOGIN_USER = '/loginUser';
const API_CHECK_SESSION_EXPIRED = '/checkExpired'
const API_GET_ALL_ACTIVE_USERS = '/getActiveUsers'
const API_GET_SESSION = '/getSession'
const API_GET_ASSIGNED_LETTERS = '/getAssignedLetters'
const API_SUBMIT_EXCHANGE_REQUEST = '/submitExchangeRequest'
const API_SUBMIT_EXCHANGE_RESPONSE = '/submitExchangeResponse'
const API_EXCHANGE_COMPLETED = '/exchangeCompleted'
const API_START_GAME = '/startGame'
const API_USER_COMPLETED_GAME = '/userCompletedGame'
const API_CHECK_AUTHENTICATED = '/checkAuthenticated'
const API_CHECK_GAME_STARTED = '/checkGameStarted'
const API_STOP_GAME = '/stopGame'

module.exports={
    API_LOGIN_USER,API_CHECK_SESSION_EXPIRED,API_GET_ALL_ACTIVE_USERS,API_GET_SESSION,API_GET_ASSIGNED_LETTERS,
    API_SUBMIT_EXCHANGE_REQUEST,API_EXCHANGE_COMPLETED,API_SUBMIT_EXCHANGE_RESPONSE,API_START_GAME,API_USER_COMPLETED_GAME,
    API_CHECK_AUTHENTICATED,API_CHECK_GAME_STARTED,API_STOP_GAME
}