const PUSHER_CHANNEL = 'iceBreaker'
const PUSHER_NEW_USER_EVENT = 'new-user'
const PUSHER_GAME_START_EVENT = 'game-start'
const PUSHER_NEW_EXCHANGE_REQUEST_EVENT = 'new-exchange-request'
const PUSHER_NEW_EXCHANGE_RESPONSE_EVENT = 'new-exchange-response'
const EXCHANGE_COMPLETED_EVENT = 'exchange-completed'

module.exports = {
    PUSHER_CHANNEL,PUSHER_NEW_USER_EVENT,PUSHER_NEW_EXCHANGE_REQUEST_EVENT,PUSHER_NEW_EXCHANGE_RESPONSE_EVENT,EXCHANGE_COMPLETED_EVENT,PUSHER_GAME_START_EVENT
}